// Fichas pessoais. IDs existentes preservados para manter cargas e registros da V13.
const DB = {
  "A": {
    "name": "Peito + Ombros + Tríceps",
    "code": "SETOR A",
    "warmup": "5–8 min de caminhada ou bike leve + 1–2 séries leves do primeiro supino.",
    "cardio": "15–20 min depois da musculação: caminhada rápida, bike ou elíptico.",
    "note": "Crucifixo na máquina fica pesado no fim: 2–3 séries são suficientes; não precisa levar tudo à falha.",
    "exercises": [
      {
        "id": "supino_inclinado",
        "name": "Supino inclinado com halteres",
        "sets": "3",
        "reps": "10–15",
        "target": "Peitoral superior",
        "secondary": "Tríceps · deltoide anterior",
        "rest": "60–90 s",
        "img": "supino-inclinado.jpg",
        "url": "https://www.youtube.com/results?search_query=supino+inclinado+com+halteres+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Apoie o tronco no banco. Use inclinação moderada e peça ajuda para posicionar os halteres se necessário; respeite sua restrição de carregar peso.",
        "unit": "reps"
      },
      {
        "id": "crucifixo_inclinado",
        "name": "Crucifixo inclinado com halteres",
        "sets": "3",
        "reps": "12–15",
        "target": "Peitoral superior",
        "secondary": "Deltoide anterior",
        "rest": "45–60 s",
        "img": "crucifixo-inclinado.jpg",
        "url": "https://www.youtube.com/results?search_query=crucifixo+inclinado+com+halteres+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Cotovelos levemente flexionados. Limite a descida à amplitude confortável do ombro.",
        "unit": "reps"
      },
      {
        "id": "supino_reto_maquina",
        "name": "Supino reto máquina",
        "sets": "3",
        "reps": "10–15",
        "target": "Peitoral",
        "secondary": "Tríceps · deltoide anterior",
        "rest": "60–90 s",
        "img": "supino-reto-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=supino+reto+m%C3%A1quina+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Regule o banco para as pegadas ficarem na linha do peito. Mantenha costas apoiadas e pés firmes.",
        "unit": "reps"
      },
      {
        "id": "crucifixo_maquina",
        "name": "Crucifixo na máquina",
        "sets": "2–3",
        "reps": "12–15",
        "target": "Peitoral",
        "secondary": "Deltoide anterior",
        "rest": "45–60 s",
        "img": "crucifixo-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=crucifixo+m%C3%A1quina+peck+deck+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Use carga controlável e não estique demais os ombros para trás. Não precisa chegar à falha.",
        "unit": "reps"
      },
      {
        "id": "elevacao_lateral",
        "name": "Elevação lateral com halteres",
        "sets": "3",
        "reps": "12–15",
        "target": "Deltoide lateral",
        "secondary": "",
        "rest": "45–60 s",
        "img": "elevacao-lateral.jpg",
        "url": "https://www.youtube.com/results?search_query=eleva%C3%A7%C3%A3o+lateral+com+halteres+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Eleve sem embalo até a altura confortável do ombro. Não compense arqueando a lombar.",
        "unit": "reps"
      },
      {
        "id": "peck_invertido",
        "name": "Peck deck invertido",
        "sets": "3",
        "reps": "12–15",
        "target": "Deltoide posterior",
        "secondary": "Romboides · trapézio médio",
        "rest": "45–60 s",
        "img": "peck-invertido.jpg",
        "url": "https://www.youtube.com/results?search_query=peck+deck+invertido+deltoide+posterior+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Apoie o peito no encosto. Abra os braços sem elevar os ombros nem jogar o tronco para trás.",
        "unit": "reps"
      },
      {
        "id": "triceps_maquina",
        "name": "Tríceps máquina",
        "sets": "3",
        "reps": "10–15",
        "target": "Tríceps",
        "secondary": "",
        "rest": "45–60 s",
        "img": "triceps-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=tr%C3%ADceps+m%C3%A1quina+muscula%C3%A7%C3%A3o+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Ajuste o banco e mantenha as costas apoiadas. Estenda os cotovelos sem mover o tronco.",
        "unit": "reps"
      }
    ],
    "family": "A",
    "variant": "Padrão",
    "focus": "Peitoral superior e movimentos de empurrar",
    "regions": [
      "chest",
      "shoulders",
      "arms"
    ],
    "duration": "45–60"
  },
  "B": {
    "name": "Costas + Bíceps + Core",
    "code": "SETOR B",
    "warmup": "5–8 min leves + 1 série de adaptação no Pulley e na remada.",
    "cardio": "Opcional: 15–20 min depois da musculação. Se estiver cansado, deixe para outro dia.",
    "note": "A remada com apoio substitui a remada curvada para facilitar a execução e reduzir a exigência de estabilização do tronco.",
    "exercises": [
      {
        "id": "pulley_frente",
        "name": "Pulley frente",
        "sets": "3",
        "reps": "12",
        "target": "Latíssimo do dorso",
        "secondary": "Bíceps",
        "rest": "60–90 s",
        "img": "pulley-frente.jpg",
        "url": "https://www.youtube.com/results?search_query=pulley+frente+puxada+pronada+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Puxe pela frente, sem levar a barra à nuca ou balançar o tronco. Para evitar polia, escolha B2.",
        "unit": "reps"
      },
      {
        "id": "puxada_triangulo",
        "name": "Puxada com triângulo",
        "sets": "3",
        "reps": "12",
        "target": "Latíssimo do dorso",
        "secondary": "Romboides · bíceps",
        "rest": "60–90 s",
        "img": "puxada-triangulo.jpg",
        "url": "https://www.youtube.com/results?search_query=puxada+alta+com+tri%C3%A2ngulo+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha o tronco estável e os cotovelos próximos do corpo. Para evitar polia, escolha B2.",
        "unit": "reps"
      },
      {
        "id": "remada_apoio",
        "name": "Remada máquina com apoio do peito",
        "sets": "3",
        "reps": "10–15",
        "target": "Costas médias",
        "secondary": "Latíssimo · romboides · trapézio médio",
        "rest": "60–90 s",
        "img": "remada-maquina-apoio.jpg",
        "url": "https://www.youtube.com/results?search_query=remada+m%C3%A1quina+apoio+peito+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha o peito apoiado durante toda a série. Puxe sem compensar com a lombar.",
        "unit": "reps"
      },
      {
        "id": "rosca_alternada",
        "name": "Rosca alternada",
        "sets": "4",
        "reps": "1×15 · 2×12 · 1×10",
        "target": "Bíceps",
        "secondary": "Braquial · braquiorradial",
        "rest": "45–60 s",
        "img": "rosca-alternada.jpg",
        "url": "https://www.youtube.com/results?search_query=rosca+alternada+halteres+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Cotovelos próximos do corpo, sem balançar o tronco. Use banco com encosto se precisar.",
        "unit": "reps"
      },
      {
        "id": "rosca_martelo",
        "name": "Rosca martelo",
        "sets": "3",
        "reps": "12",
        "target": "Braquial · braquiorradial",
        "secondary": "Bíceps",
        "rest": "45–60 s",
        "img": "rosca-martelo.jpg",
        "url": "https://www.youtube.com/results?search_query=rosca+martelo+halteres+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha pegada neutra e tronco imóvel. Use banco com encosto se precisar.",
        "unit": "reps"
      },
      {
        "id": "dead_bug",
        "name": "Dead Bug",
        "sets": "3",
        "reps": "8–10 / lado",
        "target": "Core",
        "secondary": "Estabilidade lombopélvica",
        "rest": "30–45 s",
        "img": "dead-bug.jpg",
        "url": "https://www.youtube.com/results?search_query=dead+bug+core+exerc%C3%ADcio+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Use amplitude curta, respire e mantenha o tronco estável. Pare se houver dor ou perda do controle lombar.",
        "unit": "reps"
      }
    ],
    "family": "B",
    "variant": "Padrão",
    "focus": "Puxadas verticais e costas",
    "regions": [
      "back",
      "arms",
      "core"
    ],
    "duration": "40–55"
  },
  "C": {
    "name": "Pernas + Glúteos + Core",
    "code": "SETOR C",
    "warmup": "5–8 min de caminhada ou bike leve + 1–2 séries leves na cadeira extensora.",
    "cardio": "Não é obrigatório depois deste treino. Se quiser, faça 5–10 min bem leves; o cardio principal pode ficar após A/B ou em outro dia.",
    "note": "Leg Press retirado conforme sua preferência. Exercícios apoiados ainda exigem ajuste individual de amplitude e carga.",
    "exercises": [
      {
        "id": "cadeira_adutora",
        "name": "Cadeira adutora",
        "sets": "3",
        "reps": "15",
        "target": "Adutores",
        "secondary": "Estabilizadores do quadril",
        "rest": "45–60 s",
        "img": "cadeira-adutora.jpg",
        "url": "https://www.youtube.com/results?search_query=cadeira+adutora+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha a pelve apoiada. Use amplitude confortável e feche as pernas sem impulso.",
        "unit": "reps"
      },
      {
        "id": "cadeira_abdutora",
        "name": "Cadeira abdutora",
        "sets": "3",
        "reps": "15",
        "target": "Glúteo médio",
        "secondary": "Abdutores do quadril",
        "rest": "45–60 s",
        "img": "cadeira-abdutora.jpg",
        "url": "https://www.youtube.com/results?search_query=cadeira+abdutora+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha costas e pelve apoiadas. Abra sem inclinar o tronco nem forçar a amplitude.",
        "unit": "reps"
      },
      {
        "id": "elevacao_pelvica",
        "name": "Elevação pélvica máquina / articulada",
        "sets": "3",
        "reps": "10–12",
        "target": "Glúteos",
        "secondary": "Posteriores da coxa",
        "rest": "60–90 s",
        "img": "elevacao-pelvica.jpg",
        "url": "https://www.youtube.com/results?search_query=eleva%C3%A7%C3%A3o+p%C3%A9lvica+m%C3%A1quina+hip+thrust+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Só use se já estiver liberado e confortável. Alinhe o quadril sem hiperestender a lombar.",
        "unit": "reps"
      },
      {
        "id": "cadeira_flexora",
        "name": "Cadeira flexora",
        "sets": "3",
        "reps": "10–15",
        "target": "Posteriores da coxa",
        "secondary": "",
        "rest": "45–60 s",
        "img": "cadeira-flexora.jpg",
        "url": "https://www.youtube.com/results?search_query=cadeira+flexora+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Ajuste os apoios da coxa e do tornozelo. Mantenha a pelve encostada no banco.",
        "unit": "reps"
      },
      {
        "id": "cadeira_extensora",
        "name": "Cadeira extensora",
        "sets": "4",
        "reps": "1×15 · 2×12 · 1×10",
        "target": "Quadríceps",
        "secondary": "",
        "rest": "45–60 s",
        "img": "cadeira-extensora.jpg",
        "url": "https://www.youtube.com/results?search_query=cadeira+extensora+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Alinhe o eixo da máquina com o joelho. Suba e desça com controle.",
        "unit": "reps"
      },
      {
        "id": "panturrilha_sentada",
        "name": "Panturrilha sentada na máquina",
        "sets": "3",
        "reps": "12–20",
        "target": "Panturrilhas · ênfase no sóleo",
        "secondary": "Gastrocnêmio",
        "rest": "45–60 s",
        "img": "panturrilha-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=Panturrilha%20sentada%20na%20m%C3%A1quina%20execu%C3%A7%C3%A3o%20correta",
        "cue": "Use máquina sentada, com apoio sobre as coxas. Mova os tornozelos com controle, sem impulsionar o tronco.",
        "unit": "reps",
        "reference": true
      },
      {
        "id": "bird_dog",
        "name": "Bird Dog",
        "sets": "3",
        "reps": "8–10 / lado",
        "target": "Core",
        "secondary": "Estabilidade lombopélvica",
        "rest": "30–45 s",
        "img": "bird-dog.jpg",
        "url": "https://www.youtube.com/results?search_query=bird+dog+core+exerc%C3%ADcio+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Estenda braço e perna opostos sem girar o quadril. Comece com amplitude curta.",
        "unit": "reps"
      }
    ],
    "family": "C",
    "variant": "Padrão",
    "focus": "Pernas e quadril com apoio",
    "regions": [
      "legs",
      "glutes",
      "core"
    ],
    "duration": "45–60"
  },
  "A2": {
    "name": "Peito horizontal + Ombros + Tríceps",
    "code": "SETOR A",
    "family": "A",
    "variant": "Variação",
    "focus": "Peito horizontal e deltoide lateral",
    "regions": [
      "chest",
      "shoulders",
      "arms"
    ],
    "exercises": [
      {
        "id": "supino_reto_maquina",
        "name": "Supino reto máquina",
        "sets": "3",
        "reps": "10–15",
        "target": "Peitoral",
        "secondary": "Tríceps · deltoide anterior",
        "rest": "60–90 s",
        "img": "supino-reto-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=supino+reto+m%C3%A1quina+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Regule o banco para as pegadas ficarem na linha do peito. Mantenha costas apoiadas e pés firmes.",
        "unit": "reps"
      },
      {
        "id": "crucifixo_maquina",
        "name": "Crucifixo na máquina",
        "sets": "2",
        "reps": "12–15",
        "target": "Peitoral",
        "secondary": "Deltoide anterior",
        "rest": "45–60 s",
        "img": "crucifixo-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=crucifixo+m%C3%A1quina+peck+deck+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Use carga controlável e não estique demais os ombros para trás. Não precisa chegar à falha.",
        "unit": "reps"
      },
      {
        "id": "elevacao_lateral_sentada",
        "name": "Elevação lateral sentada com encosto",
        "sets": "3",
        "reps": "12–15",
        "target": "Deltoide lateral",
        "secondary": "",
        "rest": "45–60 s",
        "img": "elevacao-lateral.jpg",
        "url": "https://www.youtube.com/results?search_query=Eleva%C3%A7%C3%A3o%20lateral%20sentada%20com%20encosto%20execu%C3%A7%C3%A3o%20correta",
        "cue": "Banco com encosto, halteres leves e pés firmes. Eleve sem impulso e sem arquear a lombar.",
        "unit": "reps",
        "reference": true
      },
      {
        "id": "triceps_maquina",
        "name": "Tríceps máquina",
        "sets": "3",
        "reps": "10–15",
        "target": "Tríceps",
        "secondary": "",
        "rest": "45–60 s",
        "img": "triceps-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=tr%C3%ADceps+m%C3%A1quina+muscula%C3%A7%C3%A3o+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Ajuste o banco e mantenha as costas apoiadas. Estenda os cotovelos sem mover o tronco.",
        "unit": "reps"
      },
      {
        "id": "peck_invertido",
        "name": "Peck deck invertido",
        "sets": "2",
        "reps": "12–15",
        "target": "Deltoide posterior",
        "secondary": "Romboides · trapézio médio",
        "rest": "45–60 s",
        "img": "peck-invertido.jpg",
        "url": "https://www.youtube.com/results?search_query=peck+deck+invertido+deltoide+posterior+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Apoie o peito no encosto. Abra os braços sem elevar os ombros nem jogar o tronco para trás.",
        "unit": "reps"
      }
    ],
    "duration": "35–45",
    "warmup": "5–8 min de caminhada ou bike leve + 1–2 séries leves do primeiro exercício.",
    "cardio": "Opcional após a musculação: 10–20 min leves a moderados, conforme disposição e orientação.",
    "note": "Substitui A. Mais espaço para o supino horizontal e os ombros, com menos movimentos repetidos para peito; sem polia."
  },
  "B2": {
    "name": "Costas médias + Bíceps + Core",
    "code": "SETOR B",
    "family": "B",
    "variant": "Variação",
    "focus": "Remadas, costas médias e deltoide posterior",
    "regions": [
      "back",
      "shoulders",
      "arms",
      "core"
    ],
    "exercises": [
      {
        "id": "remada_apoio",
        "name": "Remada máquina com apoio do peito",
        "sets": "3",
        "reps": "10–15",
        "target": "Costas médias",
        "secondary": "Latíssimo · romboides · trapézio médio",
        "rest": "60–90 s",
        "img": "remada-maquina-apoio.jpg",
        "url": "https://www.youtube.com/results?search_query=remada+m%C3%A1quina+apoio+peito+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha o peito apoiado durante toda a série. Puxe sem compensar com a lombar.",
        "unit": "reps"
      },
      {
        "id": "remada_apoio_aberta",
        "name": "Remada com apoio · pegada aberta",
        "sets": "2",
        "reps": "10–15",
        "target": "Costas médias · romboides e trapézio",
        "secondary": "Deltoide posterior · bíceps",
        "rest": "60–90 s",
        "img": "remada-maquina-apoio.jpg",
        "url": "https://www.youtube.com/results?search_query=Remada%20com%20apoio%20%C2%B7%20pegada%20aberta%20execu%C3%A7%C3%A3o%20correta",
        "cue": "Se a máquina oferecer pegada aberta, mantenha o peito apoiado e os cotovelos um pouco afastados. Não eleve os ombros ou force a amplitude.",
        "unit": "reps",
        "reference": true
      },
      {
        "id": "peck_invertido",
        "name": "Peck deck invertido",
        "sets": "2",
        "reps": "12–15",
        "target": "Deltoide posterior",
        "secondary": "Romboides · trapézio médio",
        "rest": "45–60 s",
        "img": "peck-invertido.jpg",
        "url": "https://www.youtube.com/results?search_query=peck+deck+invertido+deltoide+posterior+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Apoie o peito no encosto. Abra os braços sem elevar os ombros nem jogar o tronco para trás.",
        "unit": "reps"
      },
      {
        "id": "rosca_alternada",
        "name": "Rosca alternada",
        "sets": "2",
        "reps": "10–15",
        "target": "Bíceps",
        "secondary": "Braquial · braquiorradial",
        "rest": "45–60 s",
        "img": "rosca-alternada.jpg",
        "url": "https://www.youtube.com/results?search_query=rosca+alternada+halteres+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Cotovelos próximos do corpo, sem balançar o tronco. Use banco com encosto se precisar.",
        "unit": "reps"
      },
      {
        "id": "rosca_martelo",
        "name": "Rosca martelo",
        "sets": "2",
        "reps": "10–15",
        "target": "Braquial · braquiorradial",
        "secondary": "Bíceps",
        "rest": "45–60 s",
        "img": "rosca-martelo.jpg",
        "url": "https://www.youtube.com/results?search_query=rosca+martelo+halteres+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha pegada neutra e tronco imóvel. Use banco com encosto se precisar.",
        "unit": "reps"
      },
      {
        "id": "bird_dog",
        "name": "Bird Dog",
        "sets": "2",
        "reps": "6–8 / lado",
        "target": "Core",
        "secondary": "Estabilidade lombopélvica",
        "rest": "30–45 s",
        "img": "bird-dog.jpg",
        "url": "https://www.youtube.com/results?search_query=bird+dog+core+exerc%C3%ADcio+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Estenda braço e perna opostos sem girar o quadril. Comece com amplitude curta.",
        "unit": "reps"
      }
    ],
    "duration": "35–50",
    "warmup": "5–8 min de caminhada ou bike leve + 1–2 séries leves do primeiro exercício.",
    "cardio": "Opcional após a musculação: 10–20 min leves a moderados, conforme disposição e orientação.",
    "note": "Substitui B. Puxadas horizontais com apoio do peito; sem polia. Se a máquina não oferecer duas pegadas, pule a remada aberta."
  },
  "C2": {
    "name": "Pernas unilateral + Glúteos + Core",
    "code": "SETOR C",
    "family": "C",
    "variant": "Variação",
    "focus": "Controle de cada lado, sóleo e glúteos",
    "regions": [
      "legs",
      "glutes",
      "core"
    ],
    "exercises": [
      {
        "id": "extensora_unilateral",
        "name": "Cadeira extensora unilateral",
        "sets": "2",
        "reps": "10–15 / lado",
        "target": "Quadríceps",
        "secondary": "",
        "rest": "45–60 s",
        "img": "cadeira-extensora.jpg",
        "url": "https://www.youtube.com/results?search_query=Cadeira%20extensora%20unilateral%20execu%C3%A7%C3%A3o%20correta",
        "cue": "Somente em máquina compatível com uso unilateral. Comece leve, com o joelho alinhado ao eixo e a pelve apoiada; faça os dois lados antes de marcar a série.",
        "unit": "reps",
        "reference": true
      },
      {
        "id": "flexora_unilateral",
        "name": "Cadeira flexora unilateral",
        "sets": "2",
        "reps": "10–15 / lado",
        "target": "Posteriores da coxa",
        "secondary": "",
        "rest": "45–60 s",
        "img": "cadeira-flexora.jpg",
        "url": "https://www.youtube.com/results?search_query=Cadeira%20flexora%20unilateral%20execu%C3%A7%C3%A3o%20correta",
        "cue": "Somente em máquina compatível com uso unilateral. Mantenha a pelve apoiada e faça os dois lados antes de marcar a série.",
        "unit": "reps",
        "reference": true
      },
      {
        "id": "cadeira_abdutora",
        "name": "Cadeira abdutora",
        "sets": "2",
        "reps": "12–15",
        "target": "Glúteo médio",
        "secondary": "Abdutores do quadril",
        "rest": "45–60 s",
        "img": "cadeira-abdutora.jpg",
        "url": "https://www.youtube.com/results?search_query=cadeira+abdutora+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha costas e pelve apoiadas. Abra sem inclinar o tronco nem forçar a amplitude.",
        "unit": "reps"
      },
      {
        "id": "ponte_solo",
        "name": "Ponte de glúteos no solo",
        "sets": "2",
        "reps": "10–12",
        "target": "Glúteos",
        "secondary": "Posteriores da coxa",
        "rest": "60–90 s",
        "img": "elevacao-pelvica.jpg",
        "url": "https://www.youtube.com/results?search_query=Ponte%20de%20gl%C3%BAteos%20no%20solo%20execu%C3%A7%C3%A3o%20correta",
        "cue": "Sem carga externa e somente se liberado e confortável. Eleve o quadril sem arquear a lombar; não procure altura máxima.",
        "unit": "reps",
        "bodyweight": true,
        "reference": true
      },
      {
        "id": "panturrilha_sentada",
        "name": "Panturrilha sentada na máquina",
        "sets": "3",
        "reps": "12–20",
        "target": "Panturrilhas · ênfase no sóleo",
        "secondary": "Gastrocnêmio",
        "rest": "45–60 s",
        "img": "panturrilha-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=Panturrilha%20sentada%20na%20m%C3%A1quina%20execu%C3%A7%C3%A3o%20correta",
        "cue": "Use máquina sentada, com apoio sobre as coxas. Mova os tornozelos com controle, sem impulsionar o tronco.",
        "unit": "reps",
        "reference": true
      },
      {
        "id": "dead_bug",
        "name": "Dead Bug",
        "sets": "2",
        "reps": "6–8 / lado",
        "target": "Core",
        "secondary": "Estabilidade lombopélvica",
        "rest": "30–45 s",
        "img": "dead-bug.jpg",
        "url": "https://www.youtube.com/results?search_query=dead+bug+core+exerc%C3%ADcio+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Use amplitude curta, respire e mantenha o tronco estável. Pare se houver dor ou perda do controle lombar.",
        "unit": "reps"
      }
    ],
    "duration": "35–45",
    "warmup": "5–8 min de caminhada ou bike leve + 1–2 séries leves do primeiro exercício.",
    "cardio": "Opcional após a musculação: 10–20 min leves a moderados, conforme disposição e orientação.",
    "note": "Substitui C. Unilateral somente em máquinas compatíveis; marque a série após fazer os dois lados. Sem Leg Press, agachamento ou stiff."
  },
  "D": {
    "name": "Superiores equilibrado",
    "code": "SETOR D",
    "family": "D",
    "variant": "Alternativa",
    "focus": "Peito, costas e braços em uma sessão",
    "regions": [
      "chest",
      "back",
      "shoulders",
      "arms"
    ],
    "exercises": [
      {
        "id": "supino_reto_maquina",
        "name": "Supino reto máquina",
        "sets": "3",
        "reps": "10–15",
        "target": "Peitoral",
        "secondary": "Tríceps · deltoide anterior",
        "rest": "60–90 s",
        "img": "supino-reto-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=supino+reto+m%C3%A1quina+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Regule o banco para as pegadas ficarem na linha do peito. Mantenha costas apoiadas e pés firmes.",
        "unit": "reps"
      },
      {
        "id": "remada_apoio",
        "name": "Remada máquina com apoio do peito",
        "sets": "3",
        "reps": "10–15",
        "target": "Costas médias",
        "secondary": "Latíssimo · romboides · trapézio médio",
        "rest": "60–90 s",
        "img": "remada-maquina-apoio.jpg",
        "url": "https://www.youtube.com/results?search_query=remada+m%C3%A1quina+apoio+peito+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha o peito apoiado durante toda a série. Puxe sem compensar com a lombar.",
        "unit": "reps"
      },
      {
        "id": "elevacao_lateral_sentada",
        "name": "Elevação lateral sentada com encosto",
        "sets": "2",
        "reps": "12–15",
        "target": "Deltoide lateral",
        "secondary": "",
        "rest": "45–60 s",
        "img": "elevacao-lateral.jpg",
        "url": "https://www.youtube.com/results?search_query=Eleva%C3%A7%C3%A3o%20lateral%20sentada%20com%20encosto%20execu%C3%A7%C3%A3o%20correta",
        "cue": "Banco com encosto, halteres leves e pés firmes. Eleve sem impulso e sem arquear a lombar.",
        "unit": "reps",
        "reference": true
      },
      {
        "id": "peck_invertido",
        "name": "Peck deck invertido",
        "sets": "2",
        "reps": "12–15",
        "target": "Deltoide posterior",
        "secondary": "Romboides · trapézio médio",
        "rest": "45–60 s",
        "img": "peck-invertido.jpg",
        "url": "https://www.youtube.com/results?search_query=peck+deck+invertido+deltoide+posterior+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Apoie o peito no encosto. Abra os braços sem elevar os ombros nem jogar o tronco para trás.",
        "unit": "reps"
      },
      {
        "id": "triceps_maquina",
        "name": "Tríceps máquina",
        "sets": "2",
        "reps": "10–15",
        "target": "Tríceps",
        "secondary": "",
        "rest": "45–60 s",
        "img": "triceps-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=tr%C3%ADceps+m%C3%A1quina+muscula%C3%A7%C3%A3o+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Ajuste o banco e mantenha as costas apoiadas. Estenda os cotovelos sem mover o tronco.",
        "unit": "reps"
      },
      {
        "id": "rosca_martelo",
        "name": "Rosca martelo",
        "sets": "2",
        "reps": "10–15",
        "target": "Braquial · braquiorradial",
        "secondary": "Bíceps",
        "rest": "45–60 s",
        "img": "rosca-martelo.jpg",
        "url": "https://www.youtube.com/results?search_query=rosca+martelo+halteres+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha pegada neutra e tronco imóvel. Use banco com encosto se precisar.",
        "unit": "reps"
      }
    ],
    "duration": "35–50",
    "warmup": "5–8 min de caminhada ou bike leve + 1–2 séries leves do primeiro exercício.",
    "cardio": "Opcional após a musculação: 10–20 min leves a moderados, conforme disposição e orientação.",
    "note": "Substitui uma sessão de superiores em uma semana corrida. Não some D a A/B em dias consecutivos; preserve a recuperação."
  },
  "E": {
    "name": "Corpo inteiro · foco superiores",
    "code": "SETOR E",
    "family": "E",
    "variant": "Alternativa",
    "focus": "Superiores com manutenção de pernas",
    "regions": [
      "chest",
      "back",
      "shoulders",
      "legs",
      "core"
    ],
    "exercises": [
      {
        "id": "supino_reto_maquina",
        "name": "Supino reto máquina",
        "sets": "3",
        "reps": "10–15",
        "target": "Peitoral",
        "secondary": "Tríceps · deltoide anterior",
        "rest": "60–90 s",
        "img": "supino-reto-maquina.jpg",
        "url": "https://www.youtube.com/results?search_query=supino+reto+m%C3%A1quina+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Regule o banco para as pegadas ficarem na linha do peito. Mantenha costas apoiadas e pés firmes.",
        "unit": "reps"
      },
      {
        "id": "remada_apoio",
        "name": "Remada máquina com apoio do peito",
        "sets": "3",
        "reps": "10–15",
        "target": "Costas médias",
        "secondary": "Latíssimo · romboides · trapézio médio",
        "rest": "60–90 s",
        "img": "remada-maquina-apoio.jpg",
        "url": "https://www.youtube.com/results?search_query=remada+m%C3%A1quina+apoio+peito+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Mantenha o peito apoiado durante toda a série. Puxe sem compensar com a lombar.",
        "unit": "reps"
      },
      {
        "id": "elevacao_lateral_sentada",
        "name": "Elevação lateral sentada com encosto",
        "sets": "2",
        "reps": "12–15",
        "target": "Deltoide lateral",
        "secondary": "",
        "rest": "45–60 s",
        "img": "elevacao-lateral.jpg",
        "url": "https://www.youtube.com/results?search_query=Eleva%C3%A7%C3%A3o%20lateral%20sentada%20com%20encosto%20execu%C3%A7%C3%A3o%20correta",
        "cue": "Banco com encosto, halteres leves e pés firmes. Eleve sem impulso e sem arquear a lombar.",
        "unit": "reps",
        "reference": true
      },
      {
        "id": "cadeira_extensora",
        "name": "Cadeira extensora",
        "sets": "2",
        "reps": "12–15",
        "target": "Quadríceps",
        "secondary": "",
        "rest": "45–60 s",
        "img": "cadeira-extensora.jpg",
        "url": "https://www.youtube.com/results?search_query=cadeira+extensora+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Alinhe o eixo da máquina com o joelho. Suba e desça com controle.",
        "unit": "reps"
      },
      {
        "id": "cadeira_flexora",
        "name": "Cadeira flexora",
        "sets": "2",
        "reps": "12–15",
        "target": "Posteriores da coxa",
        "secondary": "",
        "rest": "45–60 s",
        "img": "cadeira-flexora.jpg",
        "url": "https://www.youtube.com/results?search_query=cadeira+flexora+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Ajuste os apoios da coxa e do tornozelo. Mantenha a pelve encostada no banco.",
        "unit": "reps"
      },
      {
        "id": "dead_bug",
        "name": "Dead Bug",
        "sets": "2",
        "reps": "6–8 / lado",
        "target": "Core",
        "secondary": "Estabilidade lombopélvica",
        "rest": "30–45 s",
        "img": "dead-bug.jpg",
        "url": "https://www.youtube.com/results?search_query=dead+bug+core+exerc%C3%ADcio+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o",
        "cue": "Use amplitude curta, respire e mantenha o tronco estável. Pare se houver dor ou perda do controle lombar.",
        "unit": "reps"
      }
    ],
    "duration": "35–50",
    "warmup": "5–8 min de caminhada ou bike leve + 1–2 séries leves do primeiro exercício.",
    "cardio": "Opcional após a musculação: 10–20 min leves a moderados, conforme disposição e orientação.",
    "note": "Substitui uma sessão em uma semana com menos idas à academia. Alternativa pontual; não precisa ser acrescentada ao volume de A/B/C."
  }
};

// Core e ponte usam peso corporal; não carregar uma referência de máquina.
Object.values(DB).forEach(w => w.exercises.forEach(e => { if (['dead_bug', 'bird_dog', 'ponte_solo'].includes(e.id)) e.bodyweight = true; }));

// Itens retirados da ficha seguem acessíveis nos gráficos antigos.
const ARCHIVED_EXERCISES = {C: [{"id": "leg_press", "name": "Leg Press 45°", "sets": "3", "reps": "10–12", "target": "Quadríceps", "secondary": "Glúteos", "rest": "60–90 s", "img": "leg-press.jpg", "url": "https://www.youtube.com/results?search_query=leg+press+45+execu%C3%A7%C3%A3o+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o"}, {"id": "panturrilha", "name": "Panturrilha em pé máquina", "sets": "3", "reps": "15–20", "target": "Panturrilhas", "secondary": "Gastrocnêmio · sóleo", "rest": "45–60 s", "img": "panturrilha-maquina.jpg", "url": "https://www.youtube.com/results?search_query=panturrilha+em+p%C3%A9+m%C3%A1quina+execu%C3%A7%C3%A3o+correta+muscula%C3%A7%C3%A3o"}]};
